package pdorobisz.trello.data

import org.scalaequals.ScalaEquals

sealed trait TrelloObject {
  override def equals(other: Any): Boolean = true // makes equals generated by ScalaEquals work
}

class Card(val name: String, val desc: String) extends TrelloObject {
  override def equals(other: Any): Boolean = ScalaEquals.equal

  def canEqual(other: Any): Boolean = ScalaEquals.canEquals

  override def toString: String = ScalaEquals.genString
}
